name: ESP-IDF build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_esp32_v5_1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Setup node (npm)
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - run: npm ci
    - run: npm ci
    - run: npm test
    - name: ESP-IDF v5.1 build esp32
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: release-v5.1
        target: esp32
        command: 'idf.py set-target esp32 build'
    - name: ESP-IDF v5.1 build esp32s2
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: release-v5.1
        target: esp32s2
        command: 'idf.py set-target esp32s2 build'
    - name: ESP-IDF v5.1 build esp32s3
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: release-v5.1
        target: esp32s3
        command: 'idf.py set-target esp32s3 build'
    - name: ESP-IDF v5.1 build esp32c3
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: release-v5.1
        target: esp32c3
        command: 'idf.py set-target esp32c3 build'
