name: ESP-IDF build
on:
  push:
    branches:
      - master
      - v2.0dev
  pull_request:
    branches: [ master ]

jobs:
  build_esp32_v5_1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["esp32", "esp32s2", "esp32s3", "esp32c3"]
      fail-fast: false
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: ESP-IDF v5.1 build
      uses: ./.github/actions/esp-idf-with-node
      with:
        target: "${{ matrix.target }}"
        command: "idf.py set-target ${{matrix.target}} build"
  build_esp32_v5_2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["esp32", "esp32s2", "esp32s3", "esp32c3", "esp32c6"]
      fail-fast: false
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: ESP-IDF v5.2 build
      uses: ./.github/actions/esp-idf-5_2-with-node
      with:
        target: "${{ matrix.target }}"
        command: "idf.py set-target ${{matrix.target}} build"
